id: I91CF5116
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:46:23+00:00'
last_modified: '2022-06-07T16:25:30.630036+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1EE8
  title: འཇམ་དཔལ་གྱི་མཚན་ཡང་དག་པར་བརྗོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D643:
      image_group_id: I1KG16958
      title: ''
      total_pages: 160
      order: 1
      base_file: D643.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
