id: I91CF5116
legacy_id: P002949
ocr_import_info:
  bdrc_scan_id: W1EE8
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T02:45:28'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:53:37.138891+00:00'
last_modified: 2022-08-31 03:53:47.161208
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1EE8
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1EE8
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇམ་དཔལ་གྱི་མཚན་ཡང་དག་པར་བརྗོད་པ།
statistics:
  ocr_word_mean_confidence_index: 0.4583475012059866
  ocr_word_median_confidence_index: 0.3700000047683716
quality: null
bases:
  I1KG16958:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16958
      total_pages: 160
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16958.txt
    statistics:
      ocr_word_median_confidence_index: 0.3700000047683716
      ocr_word_mean_confidence_index: 0.4583475012059866
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
