id: P002949
initial_creation_type: ocr
source_metadata:
  id: bdr:W1EE8
  title: འཇམ་དཔལ་གྱི་མཚན་ཡང་དག་པར་བརྗོད་པ།
  author: ''
  volumes:
    a25f3b7a000f4c59b200ecd50a603aaf:
      image_group_id: I1KG16958
      title: ''
      volume_number: 1
      total_pages: 160
