id: P002949
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:30:20.266491
source_metadata:
  id: bdr:W1EE8
  title: འཇམ་དཔལ་གྱི་མཚན་ཡང་དག་པར་བརྗོད་པ།
  author: ''
  volumes:
    a25f3b7a000f4c59b200ecd50a603aaf:
      image_group_id: I1KG16958
      title: ''
      volume_number: 1
      total_pages: 160
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
